services:
  mysql-test:
    deploy:
      mode: replicated # 仅在 manager 节点运行 1 个实例
      replicas: 1
      placement:
        constraints:
          - node.labels.node-type == biz_db
    volumes:
      - type: bind
        source: ~/distribute-im-gateway/deploy/data/mysql/volumes # 主机上的配置文件路径
        target: /var/lib/mysqld # 容器内的挂载路径
      - type: bind
        source: ~/distribute-im-gateway/deploy/data/mysql/my.cnf # 主机上的配置文件路径
        target: /etc/mysql/my.cnf # 容器内的挂载路径
      - type: bind
        source: ~/distribute-im-gateway/deploy/data/mysql/initSql # 主机上的配置文件路径
        target: /docker-entrypoint-initdb.d # 容器内的挂载路径


  # prometheus-test:
  #   volumes:
  #     - type: bind
  #       source: ./data/monitor/prometheus/prometheus.yml # 主机上的配置文件路径
  #       target: /etc/prometheus/prometheus.yml # 容器内的挂载路径
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.node-type == monitor
  # grafana-test:
  #   volumes:
  #     - type: bind
  #       source: ./data/monitor/grafana/volumes # 主机上的配置文件路径
  #       target: /var/lib/grafana # 容器内的挂载路径
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.node-type == monitor

  # redis-test:
  #   volumes:
  #     - type: bind
  #       source: ./data/redis/volumes # 主机上的配置文件路径
  #       target: /data # 容器内的挂载路径
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.node-type == redis

  # mysqld-exporter:
  #   volumes:
  #     - type: bind
  #       source: ./data/monitor/mysql/user_my.cnf # 主机上的配置文件路径
  #       target: /.my.cnf # 容器内的挂载路径
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.labels.node-type == monitor
