- name: 生成最新配置文件 docker-compose.yml
  shell: |
    cd ~/distribute-im-gateway
    bash deploy/docker_swarm/genDockerCompose.sh
    ls -al deploy/docker_swarm/
    cat deploy/docker_swarm/docker-compose.yml
  register: docker_compose

- name: 显示生成的配置内容
  debug:
    var: docker_compose.stdout_lines  

- name: 部署 Docker Stack
  shell: |
    cd ~/distribute-im-gateway
    ls -al deploy/docker_swarm/
    bash deploy/docker_swarm/runDockerStack.sh
  register: deploy_result

- name: 显示部署结果
  debug:
    var: deploy_result.stdout_lines
