- name: 部署 Docker Stack
  shell: |
    cd ~/distribute-im-gateway
    cat deploy/docker_swarm/docker-compose.yml
    bash deploy/docker_swarm/run.sh
  register: deploy_result

- name: 显示部署结果
  debug:
    var: deploy_result.stdout_lines
