
- name: 安装依赖的 nodejs, npx, yarn
  include_tasks: install_nodejs.yml

- name: 安装 @alexlafroscia/yaml-merge
  shell: |
    npm install -g @alexlafroscia/yaml-merge
    yaml-merge --help
  register: yaml_merge
  changed_when: false  

- name: 显示版本信息
  debug:
    msg: |
      yaml_merge: {{ yaml_merge.stdout_lines[1] }}
    