- name: Gather Docker info
  shell: docker info
  register: docker_info
  changed_when: false

- name: Initialize Swarm if not active
  shell: docker swarm init --advertise-addr {{ ansible_host }}
  register: swarm_init_result
  when: "'Swarm: active' not in docker_info.stdout"

- name: Get worker join token
  shell: docker swarm join-token worker -q
  register: worker_token_result
  when: swarm_init_result is succeeded or "'active' in (docker info | grep '^ Swarm:').split()"

- name: Set worker token as fact
  set_fact:
    worker_token: "{{ worker_token_result.stdout }}"