- name: 等待 apt 锁释放
  shell: |
    while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
      echo "等待 dpkg 锁释放..."
      sleep 5
    done
  register: apt_lock_result
  changed_when: false
  failed_when: apt_lock_result.rc not in [0, 1]
  
- name: 安装 Node.js (Debian/Ubuntu)
  apt:
    name: nodejs
    state: present
    update_cache: true
    force_apt_get: true  # 避免 apt 警告

- name: 安装 npm (Debian/Ubuntu)
  apt:
    name: npm
    state: present
    update_cache: true
    force_apt_get: true  # 避免 apt 警告    

- name: 安装全局 yarn 包
  npm:
    name: yarn
    global: true
    state: present    

    