- hosts: allNodes
  # gather_facts: yes
  vars:
    # 关键参数：
    ansible_ssh_common_args: '-o ServerAliveInterval=30 -o ServerAliveCountMax=10'
    # 延长超时时间：
    ansible_ssh_connect_timeout: 60
    ansible_timeout: 120
  roles:
    - role: allNodes

- hosts: swarm_manager
  # gather_facts: yes
  become: yes
  vars:
    # 关键参数：
    ansible_ssh_common_args: '-o ServerAliveInterval=30 -o ServerAliveCountMax=10'
    # 延长超时时间：
    ansible_ssh_connect_timeout: 60
    ansible_timeout: 120
  roles:
    - role: swarm_manager
- hosts: swarm_worker
  # gather_facts: yes
  become: yes
  vars:
    # 关键参数：
    ansible_ssh_common_args: '-o ServerAliveInterval=30 -o ServerAliveCountMax=10'
    # 延长超时时间：
    ansible_ssh_connect_timeout: 60
    ansible_timeout: 120
  roles:
    - role: swarm_worker