- hosts: swarm_worker
  tasks:
    - name: 拉取最新代码
      ansible.builtin.include_tasks: roles/allNodes/tasks/clone_latest_code.yml
    - name: 设置环境变量
      ansible.builtin.include_tasks: roles/allNodes/tasks/set_env_vars.yml

- hosts: swarm_manager
  tasks:
    - name: 生成 worker token
      ansible.builtin.include_tasks: roles/swarm_manager/tasks/gen_swarm_worker_token.yml

- hosts: swarm_worker
  tasks:
    - name: 加入成为 worker
      ansible.builtin.include_tasks: roles/swarm_worker/tasks/swarm_join.yml

- hosts: biz_db
  tasks:
    - name: 准备数据目录
      ansible.builtin.include_tasks: roles/biz_db/tasks/prepare_data_dir.yml

- hosts: swarm_manager
  tasks:
    - name: 给节点打标签
      ansible.builtin.include_tasks: roles/swarm_manager/tasks/tag_node_labels.yml
    - name: 部署 stack
      ansible.builtin.include_tasks: roles/swarm_manager/tasks/deploy_stack.yml
    - name: 查看数据库部署
      ansible.builtin.include_tasks: roles/swarm_manager/tasks/view_db_logs.yml
    - name: 显示节点标签
      ansible.builtin.include_tasks: roles/swarm_manager/tasks/show_node_labels.yml
