- name: Gather Docker info
  shell: docker info
  register: docker_info
  changed_when: false

- name: Join Swarm
  shell: docker swarm join --token {{ hostvars[groups['swarm_manager'][0]].worker_token }} {{ hostvars[groups['swarm_manager'][0]].inventory_hostname }}:2377
  when: "'Swarm: active' not in docker_info.stdout"

